# XcodeGen Project Specification for Pocket
# Run: xcodegen generate

name: Pocket

options:
  bundleIdPrefix: com.pocket
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: Pocket/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: true
    ENABLE_HARDENED_RUNTIME: NO

targets:
  Pocket:
    type: application
    platform: macOS
    sources:
      - path: Pocket
        excludes:
          - "**/*.md"
    resources:
      - path: Pocket/Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pocket.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: Pocket
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Pocket needs microphone access to listen to your voice commands."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Pocket uses speech recognition to understand your voice commands."
    entitlements:
      path: Pocket/Pocket.entitlements
      properties:
        com.apple.security.device.audio-input: true

schemes:
  Pocket:
    build:
      targets:
        Pocket: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

fileGroups:
  - Pocket
